### PR TITLE
Add CMake support to CharmLite

### PR DESCRIPTION
**Pull request by NK-Nikunj**
This PR adds the following:-

- [x] Basic CMake build system that can generate the library and build all examples
- [x] Support for Installing CharmLite
- [ ] Support for searching Charm++ through `find_package` instead of relying on environment variables
- [x] Support for creation of **FindCharmLite.cmake** to be used by CMake projects that rely on CharmLite

Random flyby:
1. Corrects incorrect use of `decode` in proxy.hpp

### CODE REVIEW

**Comment by jszaday** [comment]
1) Please put together some basic instructions on how to build with the new system (e.g., `mkdir build; cmake -G Ninja ..`, etc.).
2) The build system should _probably_ put a soft-link or copy of `$CHARM_HOME/bin/charmrun` under the `bin/` directory.
3) I'm getting the following CMake warning:
```
CMake Warning (dev) at src/CMakeLists.txt:7 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /Users/szaday2/workspace/charmlite/src/core.cc
This warning is for project developers.  Use -Wno-dev to suppress it.
```
4) There may be a linker issue (Is this using **`charmc`** to link the executables?):
```
[5/8] Linking CXX executable bin/pgm_pingpong_example
clang: warning: -Wl,-search_paths_first: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
[7/8] Linking CXX executable bin/pgm_cdt_example
clang: warning: -Wl,-search_paths_first: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
[8/8] Linking CXX executable bin/pgm_basic_example
clang: warning: -Wl,-search_paths_first: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
```

Which could explain why the examples are crashing with odd failures:
```
❯ ./charmrun ./bin/pgm_basic_example                                                                                                                                                                                                                                build -> build_system ? $

Running as 1 OS processes: ./bin/pgm_basic_example
charmrun> mpirun -np 1 ./bin/pgm_basic_example
Charm++> Running on MPI version: 3.1
Charm++> level of thread support used: -1 (desired: 0)
Charm++> Running in non-SMP mode: 1 processes (PEs)
Converse/Charm++ Commit ID: v7.1.0-devel-119-gab399e824
Charm++ built with internal error checking enabled.
Do not use for performance benchmarking (build without --enable-error-checking to do so).
Charm++> Using STL-based msgQ:
Charm++> Message priorities have been turned off and will not be respected.
[0] Stack Traceback:
  [0:0] libsystem_platform.dylib 0x1a22404e4 _sigtramp
  [0:1] pgm_basic_example 0x10255c8a4 cmk::converse_handler_(void*)
  [0:2] pgm_basic_example 0x10255c8a4 cmk::converse_handler_(void*)
------------- Processor 0 Exiting: Caught Signal ------------
Reason: Segmentation fault: 11
  [0:3] pgm_basic_example 0x102503e64 CsdScheduleForever
  [0:4] pgm_basic_example 0x1024f6e64 main
  [0:5] 0x1029510f4
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by NK-Nikunj** [comment]
Looks like you're using CMake version 3.22.1 or above (see: https://cmake.org/cmake/help/latest/policy/CMP0015.html).

Let me make corrections and push another commit.

**Comment by matthiasdiener** [comment]
> 3. I'm getting the following CMake warning:
> 
> ```
> CMake Warning (dev) at src/CMakeLists.txt:7 (add_library):
>   Policy CMP0115 is not set: Source file extensions must be explicit.  Run
>   "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   File:
> 
>     /Users/szaday2/workspace/charmlite/src/core.cc
> This warning is for project developers.  Use -Wno-dev to suppress it.
> ```

By the way, why was the `.cc` extension chosen, and not `.cpp`?

**Comment by jszaday** [comment]
> > 3. I'm getting the following CMake warning:
> > 
> > ```
> > CMake Warning (dev) at src/CMakeLists.txt:7 (add_library):
> >   Policy CMP0115 is not set: Source file extensions must be explicit.  Run
> >   "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
> >   command to set the policy and suppress this warning.
> > 
> >   File:
> > 
> >     /Users/szaday2/workspace/charmlite/src/core.cc
> > This warning is for project developers.  Use -Wno-dev to suppress it.
> > ```
> 
> By the way, why was the `.cc` extension chosen, and not `.cpp`?

I usually use it in my personal projects, which leaked through to this. As I've discussed with Nikunj, I'm fine with changing it if there's dissatisfaction.

**Comment by NK-Nikunj** [comment]
Turns out the error is not with the linking itself but the link order. Ideally libraries are linked after and not before, but our case is exactly opposite to this. I'm investigating a method that doesn't involve creating a separate cmake function call (`add_charmlite_executable`?) and can be handled normally without invoking separate `command` or `target_link_executable` et al.

**Comment by matthiasdiener** [comment]
> > By the way, why was the `.cc` extension chosen, and not `.cpp`?
> 
> I usually use it in my personal projects, which leaked through to this. As I've discussed with Nikunj, I'm fine with changing it if there's dissatisfaction.

I don't care that much, but .cpp seems to be more common than .cc or .cxx on Github:

- cpp: https://github.com/search?q=extension%3Acpp&type=Code&ref=advsearch&l=&l=
- cxx: https://github.com/search?q=extension%3Acxx&type=Code&ref=advsearch&l=&l=
- cc: https://github.com/search?q=extension%3Acc&type=Code&ref=advsearch&l=&l=

**Comment by NK-Nikunj** [comment]
Apologies for the weird named commits (Talking about **Temporary commit**), I was trying a hack to make things compile using cmake. Now that I've refactored charmlite, things work directly without any hacks. I'll rebase and force push next commit to not have pesky commit messages.

**Review by jszaday — APPROVED** [review]
LGTM!

**Pull request merged**
